import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'

// The one value the user must set after deploying. Until it is replaced, every
// absolute URL (canonical, og:url, og:image, robots.txt's Sitemap line and every
// <loc> in sitemap.xml) still points here, and both the dev server and the build
// print a warning saying so.
const PLACEHOLDER_ORIGIN = 'https://REPLACE-WITH-YOUR-DOMAIN'

/** Routes a crawler can actually visit — the project pages come from the data. */
function siteRoutes(projects) {
  return [
    '/',
    '/about',
    '/projects',
    ...projects.map((p) => `/projects/${p.slug}`),
    '/experience',
    '/education',
    '/certifications',
    '/achievements',
    '/contact',
  ]
}

/**
 * robots.txt + sitemap.xml, generated at build time (T28) so their absolute URLs
 * cannot drift from the ones in index.html.
 */
function seoFiles(origin, projects) {
  const lastmod = new Date().toISOString().slice(0, 10)
  const robots = `# ${origin}/robots.txt
# Everything here is public — crawl it all.
User-agent: *
Allow: /

Sitemap: ${origin}/sitemap.xml
`
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by vite.config.js from src/data/projects.js — do not hand-edit. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${siteRoutes(projects)
  .map((route) => `  <url>\n    <loc>${origin}${route}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </url>`)
  .join('\n')}
</urlset>
`
  const files = { '/robots.txt': robots, '/sitemap.xml': sitemap }
  return {
    name: 'seo-files',
    transformIndexHtml: {
      order: 'pre',
      handler: (html) => html.replaceAll('__SITE_ORIGIN__', origin),
    },
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const path = req.url?.split('?')[0]
        if (!path || !(path in files)) return next()
        res.setHeader('Content-Type', path.endsWith('.xml') ? 'application/xml' : 'text/plain')
        res.end(files[path])
      })
    },
    buildStart() {
      if (origin === PLACEHOLDER_ORIGIN) {
        this.warn(
          `VITE_SITE_ORIGIN is not set, so every absolute URL (canonical, og:url, og:image, ` +
            `robots.txt, sitemap.xml) still says ${PLACEHOLDER_ORIGIN}. Set it in .env or in ` +
            `Vercel → Project → Settings → Environment Variables and rebuild.`,
        )
      }
    },
    generateBundle() {
      for (const [fileName, source] of Object.entries(files)) {
        // strip the leading slash: bundle file names are relative to the output dir
        this.emitFile({ type: 'asset', fileName: fileName.slice(1), source })
      }
    },
  }
}

export default defineConfig(async ({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  const origin = (env.VITE_SITE_ORIGIN || process.env.VITE_SITE_ORIGIN || PLACEHOLDER_ORIGIN).replace(/\/+$/, '')
  const { projects } = await import('./src/data/projects.js')

  return {
    plugins: [react(), seoFiles(origin, projects)],
    build: {
      // Matches the browsers this site actually targets (React 19 / Vite 8 era):
      // no legacy transpiling of syntax the platform already understands.
      target: 'es2020',
      // Production sourcemaps stay off: nothing in the deploy needs them yet.
      sourcemap: false,
      // 500 kB: everything that must be present for the first paint lives in the
      // entry chunk — measured 458.87 kB (448.12 KiB / 140.05 KiB gzip) after route
      // splitting, of which React + the shell animation runtime are the bulk. The
      // threshold sits just above that so it stays a real tripwire: it fires if the
      // eager bundle grows, while every route page and the below-the-fold home
      // sections are separate chunks that never trip it.
      chunkSizeWarningLimit: 500,
      rolldownOptions: {
        output: {
          // Explicit, predictable names: entry + route chunks under assets/,
          // images/fonts keep their own extension.
          entryFileNames: 'assets/[name]-[hash].js',
          chunkFileNames: 'assets/[name]-[hash].js',
          assetFileNames: 'assets/[name]-[hash][extname]',
        },
      },
    },
    server: {
      host: '0.0.0.0',
      port: 5173,
      allowedHosts: true,
    },
    preview: {
      host: '0.0.0.0',
      port: 4173,
      allowedHosts: true,
    },
  }
})
